source 'https://rubygems.org'

gem 'middleman', '3.1.5', git: 'https://github.com/middleman/middleman.git'
gem 'middleman-sprockets'
gem 'middleman-minify-html'
gem 'rack-reverse-proxy'
gem 'json', '~> 1.7.7'

gem 'closure-compiler'

gem 'compass'

require 'rbconfig'
gem 'wdm', '>= 0.1.0' if RbConfig::CONFIG['target_os'] =~ /mswin|mingw|cygwin/i