package org.opencean.core.common;

public enum Parameter {

    CO2_CONCENTRATION, HUMIDITY, TEMPERATURE, SUPPLY_VOLTAGE, ILLUMINANCE, MOVEMENT, POWER, CONTACT_STATE, I, O, LEARN_BUTTON, VOC_CONCENTRATION;

}
